/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemas_distribuidos.framesCliente;

import javax.swing.JOptionPane;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import sistemas_distribuidos.helpers.ConexaoCliente;
import sistemas_distribuidos.helpers.FormatarDataHora;

/**
 *
 * @author User
 */
public class Home extends javax.swing.JFrame {

    JSONObject dadosLogin;
    String token;
    Integer id;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.dadosLogin = null;
    }

    public void setDadosLogin(JSONObject dadosLogin) throws JSONException {
        this.dadosLogin = dadosLogin;
        this.token = this.dadosLogin.getString("token");
        this.id = this.dadosLogin.getInt("id");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        btnReportarIncidente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnFiltrar = new javax.swing.JButton();
        comboEstado = new javax.swing.JComboBox<>();
        txtfData = new javax.swing.JTextField();
        txtfCidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaListagem = new javax.swing.JTextArea();
        btnAlterarCadastro = new javax.swing.JButton();
        btnIncidentesReportadosUsuario = new javax.swing.JButton();
        btnApagarConta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Home");

        btnLogout.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        btnLogout.setText("Fazer Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblWelcome.setText("Boas vindas!");

        btnReportarIncidente.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        btnReportarIncidente.setText("Reportar Incidente");
        btnReportarIncidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportarIncidenteActionPerformed(evt);
            }
        });

        jLabel2.setText("Data");

        jLabel4.setText("Estado");

        jLabel5.setText("Cidade");

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtaListagem.setEditable(false);
        txtaListagem.setColumns(20);
        txtaListagem.setRows(5);
        txtaListagem.setText(" ");
        jScrollPane1.setViewportView(txtaListagem);

        btnAlterarCadastro.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        btnAlterarCadastro.setText("Alterar Cadastro");
        btnAlterarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarCadastroActionPerformed(evt);
            }
        });

        btnIncidentesReportadosUsuario.setText("Buscar incidentes reportados por você");
        btnIncidentesReportadosUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncidentesReportadosUsuarioActionPerformed(evt);
            }
        });

        btnApagarConta.setText("Apagar sua conta");
        btnApagarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblWelcome)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtfData, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1)
                        .addGap(127, 127, 127))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(144, 144, 144)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIncidentesReportadosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReportarIncidente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAlterarCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnApagarConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(63, 63, 63))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(47, 47, 47))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnReportarIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnIncidentesReportadosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(btnAlterarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnApagarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESTADOS", "RO", "AC", "AM", "RR", "PA", "AP", "TO", "MA", "PI", "CE", "RN", "PB", "PE", "AL", "SE", "BA", "MG", "ES", "RJ", "SP", "PR", "SC", "RS", "MS", "MT", "GO", "DF" }));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        try {
            JSONObject json = new JSONObject();
            json.put("operacao", 9);
            json.put("token", token);
            json.put("id", id);
            System.out.println("Enviando mensagem: " + json + "\n através da porta: " + EscolherPorta.porta);
            JSONObject response = ConexaoCliente.ConectarServidor(json);
            String status = response.getString("status");
            if (status.equals("OK")) {
                this.setVisible(false);
                HomeVisitante homeVisitante = new HomeVisitante();
                homeVisitante.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao Realizar logout!");
                this.setVisible(true);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnReportarIncidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportarIncidenteActionPerformed
        ReportarIncidente reportarIncidente = new ReportarIncidente(token, id);
        reportarIncidente.setVisible(true);
    }//GEN-LAST:event_btnReportarIncidenteActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        String cidade = txtfCidade.getText();
        String estado = comboEstado.getSelectedItem() + "";
        String data = txtfData.getText();
        Boolean dataValidada = FormatarDataHora.validarData(data);
        txtaListagem.setText("");

        try {
            if (data.isEmpty() || cidade.isEmpty() || estado.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha todos os campos!");

            } else if (!dataValidada) {
                JOptionPane.showMessageDialog(this, "Preencha a data corretamente! yyyy-mm-dd");
            } else {
                JSONObject json = new JSONObject();
                json.put("operacao", 4);
                json.put("data", data);
                json.put("estado", estado);
                json.put("cidade", cidade.toUpperCase());

                System.out.println("Enviando mensagem: " + json + "\n através da porta: " + EscolherPorta.porta);
                JSONObject response = ConexaoCliente.ConectarServidor(json);
                String status = response.getString("status");

                if (status.equals("OK")) {
                    JOptionPane.showMessageDialog(this, "Filtrado com sucesso!");
                    JSONArray jsonArrayIncidentes = (JSONArray) response.get("incidentes");
                    if (jsonArrayIncidentes.length() == 0) {
                        txtaListagem.setText("\tNENHUM INCIDENTE FOI ENCONTRADO!");
                    } else {
                        txtaListagem.setText("\tRESULTADOS DA BUSCA SOBRE: " + cidade + " - " + estado + " DATA: " + data);
                        for (int i = 0; i < jsonArrayIncidentes.length(); i++) {
                            JSONObject incidente = jsonArrayIncidentes.getJSONObject(i);
                            Integer tipoIncidente = incidente.getInt("tipo_incidente");
                            String dataIncidente = incidente.getString("data");
                            String horaIncidente = incidente.getString("hora");
                            String cidadeIncidente = incidente.getString("cidade");
                            String bairroIncidente = incidente.getString("bairro");
                            String estadoIncidente = incidente.getString("estado");
                            String ruaIncidente = incidente.getString("rua");
                            int idIncidente = incidente.getInt("id_incidente");
                            String descIncidente;

                            switch (tipoIncidente) { 
                                case 1:
                                    descIncidente = "Alagamento";
                                    break;
                                case 2:
                                    descIncidente = "Deslizamento";
                                    break;

                                case 3:
                                    descIncidente = "Acidente de carro";
                                    break;

                                case 4:
                                    descIncidente = "Obstrução da via";
                                    break;

                                case 5:
                                    descIncidente = "Fissura da via";
                                    break;

                                case 6:
                                    descIncidente = "Pista em obras";
                                    break;

                                case 7:
                                    descIncidente = "Lentidão na pista";
                                    break;

                                case 8:
                                    descIncidente = "Animais na pista";
                                    break;

                                case 9:
                                    descIncidente = "Nevoeiro";
                                    break;

                                case 10:
                                    descIncidente = "Tromba d'água";
                                    break;
                                default:
                                    descIncidente = "Sem incidentes";
                            }

                            txtaListagem.append("\nData: " + dataIncidente + " \nHora: " + horaIncidente + " \nID: " + idIncidente + " \nTipo de Incidente: " + descIncidente + "\nCidade: " + cidadeIncidente + " - " + estadoIncidente + " \nRua: " + ruaIncidente + " \nBairro: " + bairroIncidente);
                            txtaListagem.append("\n--------------------------------------------------------------------------------------------------------------\n");

                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Erro!");
                    this.setVisible(true);
                }

            }

        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnAlterarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarCadastroActionPerformed
        AlterarCadastro alterarCadastro = new AlterarCadastro(id, token, this);
        alterarCadastro.setVisible(true);
    }//GEN-LAST:event_btnAlterarCadastroActionPerformed

    private void btnIncidentesReportadosUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncidentesReportadosUsuarioActionPerformed

        IncidentesReportadosUsuario incidentesReportadosUsuario = new IncidentesReportadosUsuario(token, this, id);
        incidentesReportadosUsuario.setVisible(true);
                
    }//GEN-LAST:event_btnIncidentesReportadosUsuarioActionPerformed

    private void btnApagarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarContaActionPerformed
       ConfirmacaoApagarConta apagarConta =  new ConfirmacaoApagarConta(token, id, this);
       apagarConta.setVisible(true);
    }//GEN-LAST:event_btnApagarContaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarCadastro;
    private javax.swing.JButton btnApagarConta;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnIncidentesReportadosUsuario;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReportarIncidente;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTextArea txtaListagem;
    private javax.swing.JTextField txtfCidade;
    private javax.swing.JTextField txtfData;
    // End of variables declaration//GEN-END:variables
}
