/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemas_distribuidos.framesCliente;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import sistemas_distribuidos.helpers.ConexaoCliente;

/**
 *
 * @author User
 */
public class IncidentesReportadosUsuario extends javax.swing.JFrame {

    String token;
    Home home;
    Integer idUsuario;

    /**
     * Creates new form IncidentesReportadosUsuario
     */
    public IncidentesReportadosUsuario() {
        initComponents();
    }

    public IncidentesReportadosUsuario(String token, Home home, Integer id) {
        this.token = token;
        this.home = home;
        this.idUsuario = id;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtfIdIncidente = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaListagem = new javax.swing.JTextArea();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Para remover um incidente, coloque seu ID ao lado: ");

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtaListagem.setEditable(false);
        txtaListagem.setColumns(20);
        txtaListagem.setRows(5);
        jScrollPane1.setViewportView(txtaListagem);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfIdIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(txtfIdIncidente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            JSONObject json = new JSONObject();
            json.put("token", token);
            json.put("id", idUsuario);
            json.put("operacao", 5);
            System.out.println(json);
            System.out.println("Enviando mensagem: " + json + "\n através da porta: " + EscolherPorta.porta);
            JSONObject response = ConexaoCliente.ConectarServidor(json);
            String status = response.getString("status");

            if (status.equals("OK")) {
                JOptionPane.showMessageDialog(this, "Filtrado com sucesso!");
                JSONArray jsonArrayIncidentes = (JSONArray) response.get("incidentes");
                if (jsonArrayIncidentes.length() == 0) {
                    txtaListagem.setText("\tNENHUM INCIDENTE FOI ENCONTRADO!");
                } else {
                    txtaListagem.setText("\tRESULTADOS DA BUSCA");
                    for (int i = 0; i < jsonArrayIncidentes.length(); i++) {
                        JSONObject incidente = jsonArrayIncidentes.getJSONObject(i);
                        Integer tipoIncidente = incidente.getInt("tipo_incidente");
                        String dataIncidente = incidente.getString("data");
                        String horaIncidente = incidente.getString("hora");
                        String cidadeIncidente = incidente.getString("cidade");
                        String bairroIncidente = incidente.getString("bairro");
                        String estadoIncidente = incidente.getString("estado");
                        String ruaIncidente = incidente.getString("rua");
                        int idIncidente = incidente.getInt("id_incidente");
                        String descIncidente;

                        switch (tipoIncidente) {
                            case 1:
                                descIncidente = "Alagamento";
                                break;
                            case 2:
                                descIncidente = "Deslizamento";
                                break;

                            case 3:
                                descIncidente = "Acidente de carro";
                                break;

                            case 4:
                                descIncidente = "Obstrução da via";
                                break;

                            case 5:
                                descIncidente = "Fissura da via";
                                break;

                            case 6:
                                descIncidente = "Pista em obras";
                                break;

                            case 7:
                                descIncidente = "Lentidão na pista";
                                break;

                            case 8:
                                descIncidente = "Animais na pista";
                                break;

                            case 9:
                                descIncidente = "Nevoeiro";
                                break;

                            case 10:
                                descIncidente = "Tromba d'água";
                                break;
                            default:
                                descIncidente = "Sem incidentes";
                        }

                        txtaListagem.append("\nData: " + dataIncidente + " \nHora: " + horaIncidente + " \nID: " + idIncidente + " \nTipo de Incidente: " + descIncidente + "\nCidade: " + cidadeIncidente + " - " + estadoIncidente + " \nRua: " + ruaIncidente + " \nBairro: " + bairroIncidente);
                        txtaListagem.append("\n--------------------------------------------------------------------------------------------------------------\n");

                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Erro!");
                this.setVisible(true);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {
            String idIncidenteString = txtfIdIncidente.getText();
            Integer id_incidente = Integer.parseInt(idIncidenteString);
            JSONObject json = new JSONObject();
            json.put("token", token);
            json.put("id", idUsuario);
            json.put("id_incidente", id_incidente);
            json.put("operacao", 6);
            System.out.println(json);
            System.out.println("Enviando mensagem: " + json + "\n através da porta: " + EscolherPorta.porta);
            JSONObject response = ConexaoCliente.ConectarServidor(json);
            String status = response.getString("status");
            if (status.equals("OK")) {
                JOptionPane.showMessageDialog(this, "Excluído com sucesso!");

            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir!");

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IncidentesReportadosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IncidentesReportadosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IncidentesReportadosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IncidentesReportadosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IncidentesReportadosUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtaListagem;
    private javax.swing.JTextField txtfIdIncidente;
    // End of variables declaration//GEN-END:variables
}
